version: '3.8'

services:
  easy-transcribe-pwa:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easy-transcribe-pwa.rule=Host(`transcribe.yourdomain.com`)"
      - "traefik.http.routers.easy-transcribe-pwa.tls=true"
      - "traefik.http.routers.easy-transcribe-pwa.tls.certresolver=letsencrypt"